// Isolated PostgreSQL checks. Never contacts the linked Supabase project.
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.env.MAREA_PGLITE_MODULE||'@electric-sql/pglite');
const db=new PGlite(); let checks=0;
const eq=(a,b,label)=>{assert.deepEqual(a,b,label);checks++;};
const rejects=async(sql)=>{await assert.rejects(db.exec(sql));checks++;};
const a='11111111-1111-4111-8111-111111111111', b='22222222-2222-4222-8222-222222222222';
const scalar=async(sql)=>Object.values((await db.query(sql)).rows[0])[0];
const system=async()=>db.exec("reset role; select set_config('request.jwt.claim.sub','',false)");
const login=async id=>db.exec(`reset role; set role authenticated; select set_config('request.jwt.claim.sub','${id}',false)`);
try {
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
create schema auth; create schema storage; grant usage on schema public,auth,storage to anon,authenticated,service_role;
create table auth.users(id uuid primary key,raw_user_meta_data jsonb not null default '{}');
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);
alter table storage.objects enable row level security; grant select,insert,update,delete on storage.objects to authenticated;
create function storage.foldername(name text) returns text[] language sql immutable as $$ select string_to_array(name,'/') $$;`);
await db.exec(await readFile(new URL('../supabase/migrations/001_initial_schema.sql',import.meta.url),'utf8'));
for(const [id,name] of [[a,'Mercado creativo'],[b,'Persona lectora']])await db.query('insert into auth.users values($1,$2)',[id,{full_name:name,username:id===a?'mercado':'persona'}]);
for(const name of ['002_account_completion','003_community','004_post_locations','005_mission_lifecycle'])await db.exec(await readFile(new URL(`../supabase/migrations/${name}.sql`,import.meta.url),'utf8'));
try{await db.exec(await readFile(new URL('../supabase/migrations/012_mission_map.sql',import.meta.url),'utf8'));}catch(e){if(e.code!=='ENOENT')throw e;}
const signature='public.list_map_missions(double precision,double precision,double precision,double precision,text,text,timestamp with time zone,timestamp with time zone,double precision,double precision,double precision)';
eq(await scalar(`select to_regprocedure('${signature}') is not null`),true,'map RPC exists');
const create=async(fields={})=>Object.values((await db.query('select public.create_mission($1::jsonb)',[{title:'Mural cercano',body:'Buscamos colaboración',category:'arte',location:'Las flores',starts_at:new Date(Date.now()+86400000).toISOString(),capacity:2,location_latitude:19.43,location_longitude:-99.13,location_precision:'approximate',...fields}])).rows[0])[0];
const search=async(extra='')=>scalar(`select public.list_map_missions(19,-100,20,-99${extra})`);
await login(a); const local=await create();
await create({title:'Punto lejano',location_latitude:22});
await create({title:'Sin coordenadas',location_latitude:null,location_longitude:null,location_precision:null});
const closed=await create({title:'Cerrada'}); await db.exec(`select public.set_mission_status('${closed}','closed',null)`);
const hidden=await create({title:'Oculta'});
const expired=await create({title:'Vencida'});
const full=await create({title:'Completa',capacity:1});
const music=await create({title:'Concierto',category:'musica',location_longitude:-99.9});
await system(); await db.exec(`update public.missions set hidden=true where id='${hidden}'; update public.missions set starts_at=now()-interval '1 day' where id='${expired}'; insert into public.mission_applications(mission_id,applicant_id,message,status) values('${full}','${b}','Participación','accepted')`);
await login(b);
let result=await search(); eq(result.total,2,'only nearby available missions'); eq(result.missions.length,2,'all nearby results returned');
eq(result.missions.find(m=>m.id===local).location_precision,'approximate','stored privacy precision preserved');
eq(result.missions[0].organizer_name,'Mercado creativo','public author display available');
eq('pending_count' in result.missions[0],false,'no private applicant statistics');
eq((await search(",category_filter=>'arte'")).total,1,'category filter');
eq((await search(",query_text=>'Mercado creativo'")).total,2,'organizer search');
eq((await search(",query_text=>'Las flores'")).total,2,'place search');
eq((await search(",query_text=>'Música'")).total,1,'localized category search');
eq((await search(",query_text=>'%'" )).total,0,'wildcard input treated literally');
eq((await search(",query_text=>'Mural'")).missions[0].id,local,'title search');
eq((await search(",center_latitude=>19.43,center_longitude=>-99.13,radius_km=>1")).total,1,'radius excludes distant part of bounds');
eq((await search(",starts_from=>now()+interval '2 days'")).total,0,'date start filter');
eq((await search(",starts_before=>now()+interval '1 hour'")).total,0,'date end is exclusive');
await rejects("select public.list_map_missions(30,-100,20,-99)");
await rejects("select public.list_map_missions('NaN',-100,20,-99)");
await rejects("select public.list_map_missions(19,-100,20,-99,radius_km=>-1)");
await rejects("select public.list_map_missions(19,-100,20,-99,radius_km=>1)");
await rejects("select public.list_map_missions(19,-100,20,-99,category_filter=>'invented')");
await login(a); await create({title:'Pacífico oeste',location_latitude:0,location_longitude:179}); await create({title:'Pacífico este',location_latitude:0,location_longitude:-179});
await login(b); eq((await scalar('select public.list_map_missions(-1,170,1,-170)')).total,2,'bounds across date line');
await system(); await db.exec(`insert into public.account_deletion_requests(user_id) values('${a}')`);
await login(b); eq((await search()).total,0,'deleting authors excluded');
await system(); await db.exec(`delete from public.account_deletion_requests where user_id='${a}'`);
await login(a);
for(let i=0;i<305;i++)await create({title:`Arte ${i}`,location_latitude:19.5});
await login(b); result=await search(); eq(result.total,307,'total counts beyond cap'); eq(result.missions.length,300,'hard result cap');
eq(new Set(result.missions.map(m=>m.id)).size,300,'cap does not duplicate missions');
await system(); await db.exec(`insert into public.account_deletion_requests(user_id) values('${b}')`); await login(b); await rejects('select public.list_map_missions(19,-100,20,-99)');
await system(); await db.exec('set role anon'); await rejects('select public.list_map_missions(19,-100,20,-99)');
eq(await scalar(`select has_function_privilege('anon','${signature}','EXECUTE')`),false,'anonymous execute denied');
console.log(`Map database: ${checks} checks passed.`);
}finally{await db.close();}
