// Local PostgreSQL/WASM verification. Never contacts hosted Supabase.
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const { PGlite } = await import(process.env.MAREA_PGLITE_MODULE || '@electric-sql/pglite');
const db = new PGlite();
let assertions = 0;
const check = (actual, expected, label) => { assert.deepEqual(actual, expected, label); assertions++; };
const rejects = async (sql, label) => { await assert.rejects(db.exec(sql), undefined, label); assertions++; };
const scalar = async (sql) => Object.values((await db.query(sql)).rows[0])[0];
const a='11111111-1111-4111-8111-111111111111', b='22222222-2222-4222-8222-222222222222', c='33333333-3333-4333-8333-333333333333', admin='44444444-4444-4444-8444-444444444444';
const login = async (id) => db.exec(`reset role; set role authenticated; select set_config('request.jwt.claim.sub','${id}',false);`);
const system = async () => db.exec(`reset role; select set_config('request.jwt.claim.sub','',false);`);
const post = (kind='community', extra='') => `insert into public.posts(kind,title,body,category,location${extra ? ',image_path' : ''}) values('${kind}','Una publicación','Una descripción','arte',${['space','event'].includes(kind) ? "'Ciudad de México'" : 'null'}${extra ? `,'${extra}'` : ''}) returning id`;
const mission = (target='null', capacity=1) => `select public.create_mission(jsonb_build_object('title','Una misión','body','Colaboración local','category','arte','location','Ciudad de México','starts_at',now()+interval '2 days','capacity',${capacity},'target_type',${target}))`;
try {
await db.exec(`
  create role anon; create role authenticated; create role service_role bypassrls;
  create schema auth; create schema storage;
  grant usage on schema public,auth,storage to anon,authenticated,service_role;
  create table auth.users(id uuid primary key,raw_user_meta_data jsonb not null default '{}');
  create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
  create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
  create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);
  alter table storage.objects enable row level security;
  grant select,insert,update,delete on storage.objects to authenticated;
  create function storage.foldername(name text) returns text[] language sql immutable as $$ select string_to_array(name,'/') $$;
`);
await db.exec(await readFile(new URL('../supabase/migrations/001_initial_schema.sql',import.meta.url),'utf8'));
for (const [id,name] of [[a,'ana'],[b,'beto'],[c,'cora'],[admin,'moderador']]) {
  await db.query('insert into auth.users(id,raw_user_meta_data) values($1,$2)',[id,{full_name:name,username:name,role:'admin'}]);
}
await db.exec(await readFile(new URL('../supabase/migrations/002_account_completion.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/003_community.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/004_post_locations.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/005_mission_lifecycle.sql',import.meta.url),'utf8'));
await db.exec(`update public.profiles set role='admin' where id='${admin}';`);
check(await scalar(`select role from public.profiles where id='${a}'`),'user','signup metadata cannot grant admin');
check((await db.query(`select public,file_size_limit,allowed_mime_types from storage.buckets where id='post-images'`)).rows[0],{public:false,file_size_limit:4194304,allowed_mime_types:['image/png']},'private PNG bucket with 4 MiB limit');
await db.exec('set role anon');
await rejects('select * from public.posts','anonymous posts denied');
await rejects('select * from public.community_profiles()','anonymous directory denied');
await login('');
await rejects('select * from public.community_profiles()','null authenticated identity denied');
await login(a);
check(await scalar('select count(*)::int from public.profiles'),1,'profiles remain owner-only');
check(await scalar('select count(*)::int from public.community_profiles()'),4,'authenticated directory');
check(Object.keys((await db.query(`select * from public.community_profiles(array['${b}'::uuid])`)).rows[0]),['id','full_name','username','bio','user_type','website'],'directory only public columns');
check(await scalar(`select count(*)::int from public.community_profiles(null,'beto')`),1,'directory name search');
await rejects(`update public.profiles set role='admin'`,'cannot spoof admin role');
for (const kind of ['project','product','service','space','event']) await rejects(post(kind),`general user cannot create ${kind}`);
const p = await scalar(post());
await db.exec(`update public.posts set location='Centro',location_latitude=19.4326,location_longitude=-99.1332,location_precision='exact' where id='${p}'`);
check(await scalar(`select location_precision from public.posts where id='${p}'`),'exact','posts accept valid exact coordinates');
await rejects(`update public.posts set location_latitude=91 where id='${p}'`,'latitude must stay within range');
await rejects(`update public.posts set location_longitude=null where id='${p}'`,'coordinates must be complete');
await rejects(`insert into public.posts(author_id,kind,title,body,category) values('${b}','community','Spoof','body','arte')`,'author column is not granted');
await rejects(`insert into public.posts(kind,title,body,category,hidden) values('community','Spoof','body','arte',true)`,'hidden insertion denied');
await rejects(`update public.posts set kind='product' where id='${p}'`,'kind reassignment denied');
await rejects(`update public.posts set author_id='${b}' where id='${p}'`,'author reassignment denied');
await rejects(`update public.posts set hidden=true where id='${p}'`,'visibility update denied');
await rejects(`update public.posts set price=250 where id='${p}'`,'non-commercial posts cannot have prices');
await rejects(`update public.posts set price=-1 where id='${p}'`,'negative price rejected');
await rejects(`update public.posts set price=100000000 where id='${p}'`,'price maximum enforced');
await rejects(`update public.posts set title='ab' where id='${p}'`,'short title rejected');
await rejects(`update public.posts set body=repeat('a',3001) where id='${p}'`,'body maximum enforced');
await rejects(`update public.posts set title='Valid'||repeat(' ',1000) where id='${p}'`,'whitespace cannot bypass maximum');
await rejects(`update public.posts set category='unknown' where id='${p}'`,'unknown category rejected');
for (const [type,kinds] of [['Artista / creador',['project']],['Emprendedor',['product','service']],['Negocio',['space','event']]]) {
  await db.exec(`update public.profiles set user_type='${type}' where id='${a}';`);
  for (const kind of kinds) await scalar(post(kind));
}
await rejects(`update public.posts set location=null where kind='space'`,'space requires a location');
await rejects(`update public.posts set location='   ' where kind='event'`,'event requires nonblank location');
await rejects(`update public.posts set price=1 where kind='project'`,'project cannot have price');
await db.exec(`update public.posts set price=250 where kind in ('product','service');`);
check(await scalar(`select count(*)::int from public.posts where price=250`),2,'product and service accept valid prices');
await db.exec(`update public.profiles set user_type='Usuario general' where id='${a}'; update public.posts set title='Edición persistente' where kind='project';`);
check(await scalar(`select title from public.posts where kind='project'`),'Edición persistente','type changes preserve existing post edits');
await login(b);
check(await scalar(`select count(*)::int from public.posts`),6,'other users see visible posts');
await db.exec(`update public.posts set title='Ataque' where id='${p}'; delete from public.posts where id='${p}';`);
check(await scalar(`select title from public.posts where id='${p}'`),'Una publicación','cross-owner update/delete have no effect');
await db.exec(`insert into public.post_saves(post_id) values('${p}');`);
await rejects(`insert into public.post_saves(post_id) values('${p}')`,'duplicate save rejected');
await login(a);
check(await scalar('select count(*)::int from public.post_saves'),0,'saves are private');
await rejects(`select public.moderate_content('${p}','post',true)`,'non-admin moderation denied');
await login(b);
await db.exec(`insert into public.content_reports(post_id,reason) values('${p}','Contenido inapropiado');`);
await rejects(`insert into public.content_reports(post_id,reason) values('${p}','Segundo reporte')`,'duplicate report denied');
await rejects(`insert into public.content_reports(post_id,reason,state) values('${p}','Contenido','resolved')`,'report state spoof denied');
await login(a);
check(await scalar('select count(*)::int from public.content_reports'),0,'reports private to reporter and admins');
await login(admin);
check(await scalar('select count(*)::int from public.content_reports'),1,'admin reads reports');
await rejects(post('project'),'admin does not receive type-specific creation privileges');
await db.exec(`select public.moderate_content('${p}','post',true)`);
check(await scalar('select state from public.content_reports'),'resolved','moderation resolves reports');
await login(c);
check(await scalar(`select count(*)::int from public.posts where id='${p}'`),0,'hidden posts invisible to third party');
await rejects(`insert into public.post_saves(post_id) values('${p}')`,'cannot save hidden post');
await rejects(`insert into public.content_reports(post_id,reason) values('${p}','Invisible target')`,'cannot report hidden target');
await login(a);
check(await scalar(`select count(*)::int from public.posts where id='${p}'`),1,'owner sees hidden content');
const image=`${a}/55555555-5555-4555-8555-555555555555.png`;
await db.exec(`insert into storage.objects(bucket_id,name) values('post-images','${image}');`);
await rejects(`insert into storage.objects(bucket_id,name) values('post-images','${b}/55555555-5555-4555-8555-555555555555.png')`,'foreign upload denied');
await rejects(`insert into storage.objects(bucket_id,name) values('post-images','${a}/bad.jpg')`,'non-PNG path denied');
await login(b);
check(await scalar(`select count(*)::int from storage.objects where name='${image}'`),0,'unattached image private');
await rejects(post('community',image),'foreign image attachment denied');
await login(a);
await db.exec(`update public.posts set image_path='${image}' where id='${p}'; delete from storage.objects where name='${image}';`);
check(await scalar(`select count(*)::int from storage.objects where name='${image}'`),1,'referenced image cannot be deleted');
await login(b);
check(await scalar(`select count(*)::int from storage.objects where name='${image}'`),0,'hidden post image private');
await login(admin);
check(await scalar(`select count(*)::int from storage.objects where name='${image}'`),1,'admin can inspect hidden content image');
await db.exec(`select public.moderate_content('${p}','post',false)`);
await login(b);
check(await scalar(`select count(*)::int from storage.objects where name='${image}'`),1,'visible post image readable');
await login(a);
const m = await scalar(mission());
const targeted = await scalar(mission("'Artista / creador'"));
await rejects(`insert into public.missions(title,body,category,location,starts_at,capacity) values('Pasado','Texto','arte','CDMX',now()-interval '1 day',1)`,'past creation denied');
await rejects(`insert into public.missions(title,body,category,location,starts_at,capacity) values('Capacidad','Texto','arte','CDMX',now()+interval '1 day',0)`,'capacity range enforced');
await rejects(`select public.apply_to_mission('${m}','Yo mismo')`,'self apply denied');
await rejects(`update public.missions set status='closed' where id='${m}'`,'direct mission status mutation denied');
await rejects(`insert into public.content_reports(post_id,mission_id,reason) values('${p}','${m}','Two targets denied')`,'report must identify exactly one target');
await rejects(`insert into public.content_reports(reason) values('Missing target')`,'report requires a target');
await login(b);
await rejects(`select public.apply_to_mission('${targeted}','Me interesa')`,'target type enforced');
await rejects(`select public.apply_to_mission('${m}','')`,'empty application denied');
const appB = await scalar(`select public.apply_to_mission('${m}','Me interesa colaborar')`);
await rejects(`select public.apply_to_mission('${m}','Duplicada')`,'duplicate application rejected');
await rejects(`insert into public.mission_applications(mission_id,applicant_id,message) values('${m}','${b}','Directo')`,'application direct writes denied');
await rejects(`select public.set_mission_status('${m}','closed')`,'non-owner cannot close mission');
await rejects(`select public.review_application('${appB}','accepted')`,'applicant cannot accept own application');
await login(c);
check(await scalar('select count(*)::int from public.mission_applications'),0,'other applicants cannot read application');
await rejects(`select public.withdraw_application('${appB}')`,'cannot withdraw another application');
const appC = await scalar(`select public.apply_to_mission('${m}','Me interesa también')`);
await login(admin);
check(await scalar('select count(*)::int from public.mission_applications'),0,'admin does not read private applications');
await login(a);
check(await scalar('select count(*)::int from public.mission_applications'),2,'owner reads mission applications');
await rejects(`select public.review_application('${appB}','pending')`,'invalid decision denied');
await db.exec(`select public.review_application('${appB}','accepted'); select public.review_application('${appB}','accepted');`);
await rejects(`select public.review_application('${appC}','accepted')`,'cannot exceed accepted capacity');
check(await scalar(`select count(*)::int from public.mission_applications where status='accepted'`),1,'capacity remains bounded');
await db.exec(`select public.set_mission_status('${m}','closed')`);
await rejects(`select public.review_application('${appC}','accepted')`,'closed review still respects capacity');
await login(b);
await db.exec(`select public.withdraw_application('${appB}')`);
check(await scalar(`select count(*)::int from public.mission_applications where status='withdrawn'`),1,'withdraw retains own application history');
await rejects(`select public.apply_to_mission('${m}','Otra vez')`,'closed mission cannot apply');
await login(a);
await db.exec(`select public.set_mission_status('${m}','open'); select public.review_application('${appC}','accepted');`);
check(await scalar(`select status from public.mission_applications where id='${appC}'`),'accepted','withdrawal releases accepted slot');
await login(b);
await rejects(`select public.apply_to_mission('${m}','Sin cupo')`,'full mission cannot apply');
await login(c);
await db.exec(`select public.withdraw_application('${appC}')`);
await login(admin);
await db.exec(`select public.moderate_content('${m}','mission',true)`);
await login(b);
check(await scalar(`select count(*)::int from public.missions where id='${m}'`),0,'hidden mission invisible');
await rejects(`select public.apply_to_mission('${m}','Oculta')`,'hidden mission cannot apply');
await login(admin);
await db.exec(`select public.moderate_content('${m}','mission',false)`);
await system();
await db.exec(`alter table public.missions disable trigger validate_mission_lifecycle; update public.missions set starts_at=now()-interval '1 hour' where id='${m}'; alter table public.missions enable trigger validate_mission_lifecycle;`);
await login(b);
await rejects(`select public.apply_to_mission('${m}','Tarde')`,'deadline enforced for apply');
await login(a);
await rejects(`select public.set_mission_status('${m}','open')`,'expired mission cannot reopen');
await db.exec(`update public.posts set image_path=null where id='${p}'; delete from storage.objects where name='${image}';`);
check(await scalar(`select count(*)::int from storage.objects where name='${image}'`),0,'unused own image deletable');
// Target eligibility is rechecked at selection time, after account-type changes.
await login(b);
await db.exec(`update public.profiles set user_type='Artista / creador' where id='${b}'`);
const targetApp = await scalar(`select public.apply_to_mission('${targeted}','Proyecto creativo')`);
await db.exec(`update public.profiles set user_type='Usuario general' where id='${b}'`);
await login(a);
await rejects(`select public.review_application('${targetApp}','accepted')`,'target eligibility rechecked at acceptance');
await db.exec(`select public.review_application('${targetApp}','rejected')`);
await login(b);
await rejects(`select public.apply_to_mission('${targeted}','Otra solicitud')`,'rejected application cannot be duplicated');
await db.exec(`update public.profiles set user_type='Artista / creador' where id='${b}'`);
await rejects(`select public.apply_to_mission('${targeted}','Otra solicitud')`,'rejected eligible application remains unique');
await login(a);
await db.exec(`select public.review_application('${targetApp}','accepted')`);
check(await scalar(`select status from public.mission_applications where id='${targetApp}'`),'accepted','owner may revise rejected application within capacity');
await system();
await db.exec(`alter table public.missions disable trigger validate_mission_lifecycle; update public.missions set starts_at=now()-interval '1 hour' where id='${targeted}'; alter table public.missions enable trigger validate_mission_lifecycle;`);
await login(a);
await rejects(`select public.review_application('${targetApp}','rejected')`,'deadline enforced for selection');
// Deletion marker and image creation use the same account advisory lock.
await system();
check(await scalar(`select request_account_deletion('${a}')`),true,'deletion marker ready');
await login(a);
await rejects(`insert into storage.objects(bucket_id,name) values('post-images','${image}')`,'upload blocked after deletion marker');
await rejects(post(),'post create blocked after deletion marker');
await rejects(mission(),'mission create blocked after deletion marker');
await rejects(`select public.apply_to_mission('${targeted}','Pending account')`,'pending deletion account cannot apply');
await system();
check(await scalar('select count(*)::int from public.mission_applications'),3,'retained application fixtures before cascade');
await db.exec(`delete from auth.users where id='${a}'`);
check(await scalar(`select count(*)::int from public.posts where author_id='${a}'`),0,'posts cascade with account deletion');
check(await scalar(`select count(*)::int from public.missions where author_id='${a}'`),0,'missions cascade with account deletion');
check(await scalar('select count(*)::int from public.post_saves'),0,'saves cascade with deleted post');
check(await scalar('select count(*)::int from public.content_reports'),0,'reports cascade with deleted target');
check(await scalar('select count(*)::int from public.mission_applications'),0,'applications cascade with deleted mission');
console.log(`${assertions} community database assertions passed (isolated PostgreSQL via PGlite; hosted Supabase not contacted).`);
} finally { await db.close(); }
