// Local PostgreSQL/WASM verification. Never contacts hosted Supabase.
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const { PGlite } = await import(process.env.MAREA_PGLITE_MODULE || '@electric-sql/pglite');
const db = new PGlite();
let assertions = 0;
const check = (actual, expected, label) => { assert.deepEqual(actual, expected, label); assertions++; };
const rejects = async (sql, label) => { await assert.rejects(db.exec(sql), undefined, label); assertions++; };
const scalar = async (sql) => Object.values((await db.query(sql)).rows[0])[0];
const a='11111111-1111-4111-8111-111111111111', b='22222222-2222-4222-8222-222222222222', c='33333333-3333-4333-8333-333333333333', admin='44444444-4444-4444-8444-444444444444';
const login = async (id) => db.exec(`reset role; set role authenticated; select set_config('request.jwt.claim.sub','${id}',false);`);
const system = async () => db.exec(`reset role; select set_config('request.jwt.claim.sub','',false);`);
const post = (kind='community', extra='') => `insert into public.posts(kind,title,body,category,location${extra ? ',image_path' : ''}) values('${kind}','Una publicación','Una descripción','arte',${['space','event'].includes(kind) ? "'Ciudad de México'" : 'null'}${extra ? `,'${extra}'` : ''}) returning id`;
const mission = (target='null', capacity=1) => `insert into public.missions(title,body,category,location,starts_at,capacity,target_type) values('Una misión','Colaboración local','arte','Ciudad de México',now()+interval '2 days',${capacity},${target}) returning id`;
try {
await db.exec(`
  create role anon; create role authenticated; create role service_role bypassrls;
  create schema auth; create schema storage;
  grant usage on schema public,auth,storage to anon,authenticated,service_role;
  create table auth.users(id uuid primary key,raw_user_meta_data jsonb not null default '{}');
  create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
  create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
  create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);
  alter table storage.objects enable row level security;
  grant select,insert,update,delete on storage.objects to authenticated;
  create function storage.foldername(name text) returns text[] language sql immutable as $$ select string_to_array(name,'/') $$;
`);
await db.exec(await readFile(new URL('../supabase/migrations/001_initial_schema.sql',import.meta.url),'utf8'));
for (const [id,name] of [[a,'ana'],[b,'beto'],[c,'cora'],[admin,'moderador']]) {
  await db.query('insert into auth.users(id,raw_user_meta_data) values($1,$2)',[id,{full_name:name,username:name,role:'admin'}]);
}
await db.exec(await readFile(new URL('../supabase/migrations/002_account_completion.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/003_community.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/004_post_locations.sql',import.meta.url),'utf8'));
await db.exec(`update public.profiles set role='admin' where id='${admin}';`);
// Fixtures accepted by old migrations must be upgraded without losing text.
const legacyPost=await scalar(`insert into public.posts(author_id,kind,title,body,category,location,location_latitude) values('${a}','community','Legacy location','Texto','arte','Centro',19) returning id`);
const legacyMission=await scalar(`insert into public.missions(author_id,title,body,category,location,starts_at,capacity) values('${a}','Legacy mission','Texto','arte','CDMX',now()+interval '2 days',3) returning id`);
await db.exec(`insert into public.mission_applications(mission_id,applicant_id,message) values('${legacyMission}','${b}','Antes de migración')`);
try { await db.exec(await readFile(new URL('../supabase/migrations/005_mission_lifecycle.sql',import.meta.url),'utf8')); } catch (e) { if (e.code !== 'ENOENT') throw e; }

// RPCs are callable only by authenticated users; internal guards stay private.
for (const signature of ['create_mission(jsonb)','update_mission(uuid,jsonb)','set_mission_status(uuid,text,text)','list_missions(uuid,text,text,text,text,integer,uuid)','apply_to_mission(uuid,text)','withdraw_application(uuid)','review_application(uuid,text)']) {
  check(await scalar(`select has_function_privilege('authenticated','public.${signature}','EXECUTE')`),true,`${signature} is available to authenticated users`);
  check(await scalar(`select has_function_privilege('anon','public.${signature}','EXECUTE')`),false,`${signature} denied to anonymous users`);
}
for (const signature of ['validate_mission_lifecycle()','guard_mission_image_operation()','community_active_account()']) {
  check(await scalar(`select has_function_privilege('authenticated','public.${signature}','EXECUTE')`),false,`${signature} cannot be called directly`);
}
for (const col of ['status','capacity','author_id','conditions_locked_at','hidden']) {
  check(await scalar(`select has_column_privilege('authenticated','public.missions','${col}','UPDATE')`),false,`${col} cannot be updated directly`);
}
check(await scalar(`select has_column_privilege('authenticated','public.missions','title','INSERT')`),false,'direct mission inserts have no column grant');
check(await scalar(`select bool_and(prosecdef and proconfig @> array['search_path=""']) from pg_proc where pronamespace='public'::regnamespace and proname in ('create_mission','update_mission','list_missions','set_mission_status')`),true,'definer RPCs have empty search path');
await login(a);
const input={title:'Misión creativa',body:'Colaboración local',category:'arte',location:'CDMX',starts_at:new Date(Date.now()+86400000).toISOString(),capacity:1};
const rpcCreate=async (fields={}) => Object.values((await db.query('select public.create_mission($1::jsonb)',[{...input,...fields}])).rows[0])[0];
const edit=async (id,fields) => db.query('select public.update_mission($1,$2::jsonb)',[id,fields]);
const row=async id => (await db.query('select * from public.missions where id=$1',[id])).rows[0];
const listing=async (id,scope='all') => (await db.query('select * from public.list_missions(mission_filter => $1,scope_filter => $2)',[id,scope])).rows.map(r=>r.list_missions);
check(await scalar(`select count(*)::int from information_schema.routines where routine_schema='public' and routine_name='create_mission'`),1,'create RPC exists');
check(await scalar(`select location from public.posts where id='${legacyPost}'`),'Centro','upgrade preserves legacy location text');
check(await scalar(`select location_latitude from public.posts where id='${legacyPost}'`),null,'upgrade removes partial coordinates');
assert.ok((await row(legacyMission)).conditions_locked_at); assertions++;
await assert.rejects(edit(legacyMission,{location:'Cambio'})); assertions++;
const m=await rpcCreate();
await edit(m,{capacity:2});
await edit(m,{capacity:1});
check((await row(m)).capacity,1,'capacity may shrink before first application');
await assert.rejects(edit(m,{requirements:'a'.repeat(3001)})); assertions++;
await assert.rejects(edit(m,{conditions:'a'.repeat(3001)})); assertions++;
await assert.rejects(edit(m,{author_id:b})); assertions++;
await assert.rejects(edit(m,{conditions_locked_at:null})); assertions++;
await assert.rejects(rpcCreate({location_latitude:'Infinity',location_longitude:0,location_precision:'exact'})); assertions++;
await assert.rejects(rpcCreate({location_latitude:0,location_longitude:'NaN',location_precision:'exact'})); assertions++;
await assert.rejects(edit(m,{location_latitude:19.4})); assertions++;
await edit(m,{location_latitude:19.4,location_longitude:-99.1,location_precision:'exact',requirements:'Trae cámara',conditions:'Respeto'});
check((await row(m)).location_latitude,19.4,'optional complete coordinates saved');
await assert.rejects(rpcCreate({starts_at:'2000-01-01'})); assertions++;
await assert.rejects(rpcCreate({status:'completed'})); assertions++;
await rejects(mission(),'direct creation is revoked');
await rejects(`update public.missions set capacity=100 where id='${m}'`,'direct editing denied');
await rejects(`select public.set_mission_status('${m}','completed')`,'cannot complete before start');
await login(b);
await assert.rejects(edit(m,{title:'Attacker'})); assertions++;
check((await listing(m))[0].pending_count,null,'pending count private');
check(Object.keys((await listing(m))[0]).filter(k=>/email|applicant|application|reporter|role/.test(k)),[],'listing exposes no participant identities or private profile fields');
check((await listing(m))[0].organizer_username,'ana','safe organizer name available');
const app=await scalar(`select public.apply_to_mission('${m}','Colaboro')`);
await rejects(`select public.apply_to_mission('${m}','Duplicado')`,'duplicate active application blocked');
await login(a);
check((await listing(m))[0].pending_count,1,'owner sees pending count');
const locked=(await row(m)).conditions_locked_at;
assert.ok(locked); assertions++;
for(const patch of [{starts_at:new Date(Date.now()+172800000).toISOString()},{location:'Puebla'},{location_latitude:20},{target_type:'Negocio'}]) { await assert.rejects(edit(m,patch)); assertions++; }
await edit(m,{capacity:2,title:'Título editable',requirements:'Nuevo texto',conditions:'Nueva descripción'});
await assert.rejects(edit(m,{capacity:1})); assertions++;
await db.exec(`select public.set_mission_status('${m}','closed'); select public.review_application('${app}','accepted');`);
check((await listing(m))[0].accepted_count,1,'closed review accepts and count public');
await login(b);
await db.exec(`select public.withdraw_application('${app}')`);
check(await scalar(`select status from public.mission_applications where id='${app}'`),'withdrawn','withdraw retains history');
await login(a);
check((await row(m)).conditions_locked_at,locked,'lock remains after withdrawal');
await rejects(`select public.review_application('${app}','accepted')`,'cannot review withdrawn application');
await db.exec(`select public.set_mission_status('${m}','open')`);
await login(b);
check(await scalar(`select public.apply_to_mission('${m}','Regreso')`),app,'reapply reuses withdrawn row');
await login(a);
await db.exec(`select public.review_application('${app}','accepted')`);
await login(c);
const appC=await scalar(`select public.apply_to_mission('${m}','También')`);
check(await scalar(`select count(*)::int from public.mission_applications where id='${app}'`),0,'applications remain private');
await login(a);
await db.exec(`select public.review_application('${appC}','accepted')`);
await login(c);
check((await listing(m,'discover')).length,1,'discover includes full mission');
check((await listing(m))[0].accepted_count,2,'public accepted count');
await login(admin);
await rejects(`select public.apply_to_mission('${m}','Sin cupo')`,'full accepted capacity prevents more applications');
check((await listing(m))[0].pending_count,0,'admin gets aggregate pending count');
await rejects(`select public.set_mission_status('${m}','cancelled','Moderador')`,'admin cannot cancel another mission');
await login(a);
await rejects(`select public.set_mission_status('${m}','cancelled')`,'cancellation requires reason');
await rejects(`select public.set_mission_status('${m}','cancelled','No')`,'cancellation reason minimum');
await db.exec(`select public.set_mission_status('${m}','cancelled','Lluvia')`);
check((await row(m)).cancellation_reason,'Lluvia','cancellation reason persisted');
await rejects(`select public.set_mission_status('${m}','open')`,'terminal cancellation irreversible');
await assert.rejects(edit(m,{title:'Cambio tardío'})); assertions++;
check((await listing(m,'active')).length,0,'terminal mission absent from active');
check((await listing(m,'history')).length,1,'terminal mission in history');
await login(b);
await rejects(`select public.withdraw_application('${app}')`,'terminal participation preserved');
await rejects(`select public.apply_to_mission('${m}','Tarde')`,'terminal apply denied');
await login(a);
const done=await rpcCreate();
await system();
await db.exec(`update public.missions set starts_at=now()-interval '1 hour' where id='${done}'`);
await login(a);
await db.exec(`select public.set_mission_status('${done}','completed')`);
await rejects(`select public.set_mission_status('${done}','cancelled','Cambio')`,'completed irreversible');
const image=`${a}/55555555-5555-4555-8555-555555555555.png`;
await db.exec(`insert into storage.objects(bucket_id,name) values('mission-images','${image}')`);
await system();
check((await db.query(`select public,file_size_limit,allowed_mime_types from storage.buckets where id='mission-images'`)).rows[0],{public:false,file_size_limit:4194304,allowed_mime_types:['image/png']},'mission bucket is private PNG with 4MiB limit');
await login(a);
await rejects(`insert into storage.objects(bucket_id,name) values('mission-images','${a}/bad.jpg')`,'mission image names must be UUID PNG');
await db.exec(`update storage.objects set name='${a}/66666666-6666-4666-8666-666666666666.png' where bucket_id='mission-images' and name='${image}'`);
check(await scalar(`select count(*)::int from storage.objects where bucket_id='mission-images' and name='${image}'`),1,'authenticated storage update has no policy');
const photo=await rpcCreate({image_path:image});
await system();
await rejects(`update storage.objects set bucket_id='elsewhere' where bucket_id='mission-images' and name='${image}'`,'storage guard blocks moving mission images');
await login(a);
await db.exec(`delete from storage.objects where bucket_id='mission-images' and name='${image}'`);
check(await scalar(`select count(*)::int from storage.objects where bucket_id='mission-images' and name='${image}'`),1,'in-use image protected');
await login(b);
check(await scalar(`select count(*)::int from storage.objects where bucket_id='mission-images' and name='${image}'`),1,'visible mission image readable');
await assert.rejects(rpcCreate({image_path:image})); assertions++;
await rejects(`insert into storage.objects(bucket_id,name) values('mission-images','${a}/66666666-6666-4666-8666-666666666666.png')`,'foreign image upload denied');
await login(admin);
await db.exec(`select public.moderate_content('${photo}','mission',true)`);
check((await listing(photo)).length,1,'admin listing includes hidden missions');
await login(b);
check((await listing(photo)).length,0,'definer listing excludes hidden mission');
check(await scalar(`select count(*)::int from storage.objects where bucket_id='mission-images' and name='${image}'`),0,'hidden mission image private');
await login(a);
check((await listing(photo)).length,1,'owner sees hidden mission');
check((await listing(photo,'discover')).length,0,'discover excludes hidden for owner');
await edit(photo,{image_path:null});
await db.exec(`delete from storage.objects where bucket_id='mission-images' and name='${image}'`);
check(await scalar(`select count(*)::int from storage.objects where bucket_id='mission-images' and name='${image}'`),0,'unattached own image removable');
const p=await scalar(post());
await rejects(`update public.posts set location_latitude=19 where id='${p}'`,'partial legacy coordinates rejected');
await rejects(`update public.posts set location_latitude='NaN',location_longitude=0,location_precision='exact' where id='${p}'`,'NaN rejected');
await rejects(`update public.posts set location_latitude=0,location_longitude='Infinity',location_precision='exact' where id='${p}'`,'infinite coordinates rejected');
// Filtering happens before pagination, with deterministic date/id ordering.
for(let i=0;i<33;i++) await rpcCreate({title:`Filtro ${i}`,category:i<3?'musica':'arte'});
check(await scalar(`select count(*)::int from public.list_missions(query_text=>'Filtro',category_filter=>'musica',scope_filter=>'discover')`),3,'filter before limit');
check(await scalar(`select count(*)::int from public.list_missions(query_text=>'Filtro',page_offset=>30)`),3,'offset pagination');
await rejects(`select * from public.list_missions(scope_filter=>'unknown')`,'invalid scope rejected');
await system();
check(await scalar(`select request_account_deletion('${a}')`),true,'deletion marker set');
await login(a);
await assert.rejects(rpcCreate()); assertions++;
await assert.rejects(edit(photo,{title:'Deletion race'})); assertions++;
await login(b);
check(await scalar(`select count(*)::int from public.list_missions(author_filter=>'${a}')`),0,'deleting organizer excluded from discovery');
await login(a);
await rejects(`insert into storage.objects(bucket_id,name) values('mission-images','${image}')`,'deletion marker blocks image creation');
await system();
await db.exec(`delete from auth.users where id='${a}'`);
check(await scalar('select count(*)::int from public.missions'),0,'mission deletion cascades');
check(await scalar('select count(*)::int from public.mission_applications'),0,'application deletion cascades');
await login('');
await rejects('select * from public.list_missions()','null identity listing denied');
await system();
await db.exec('set role anon');
await rejects('select * from public.list_missions()','anonymous listing denied');
console.log(`${assertions} mission lifecycle assertions passed (isolated PGlite; hosted Supabase not contacted).`);
} finally { await db.close(); }
