// Local Postgres/WASM validation only; never connects to a hosted database.
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const { PGlite } = await import(process.env.MAREA_PGLITE_MODULE || '@electric-sql/pglite');
const db = new PGlite();
let assertions = 0;
const check = (actual, expected, label) => { assert.deepEqual(actual, expected, label); assertions++; };
const rejects = async (sql, label) => { await assert.rejects(db.exec(sql), undefined, label); assertions++; };
await db.exec(`
  create role anon; create role authenticated; create role service_role bypassrls;
  create schema auth; create schema storage;
  grant usage on schema public,auth,storage to anon,authenticated,service_role;
  create table auth.users(id uuid primary key, raw_user_meta_data jsonb not null default '{}');
  create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
  create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
  create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);
  alter table storage.objects enable row level security;
  grant select on storage.objects to authenticated;
  create function storage.foldername(name text) returns text[] language sql immutable as $$ select string_to_array(name,'/') $$;
`);
await db.exec(await readFile(new URL('../supabase/migrations/001_initial_schema.sql', import.meta.url), 'utf8'));
const a = '11111111-1111-4111-8111-111111111111', b = '22222222-2222-4222-8222-222222222222';
await db.exec(`insert into auth.users values('${a}','{"full_name":"Ana","username":"ana"}');`);
await db.exec(await readFile(new URL('../supabase/migrations/002_account_completion.sql', import.meta.url), 'utf8'));
check((await db.query('select count(*)::int as n from public.profiles')).rows[0].n, 1, 'legacy profiles preserved');
check((await db.query('select count(*)::int as n from public.legal_acceptances')).rows[0].n, 0, 'legacy acceptance is never fabricated');
check((await db.query('select registration_policy() as p')).rows[0].p.signup_enabled, false, 'closed by default');
await rejects(`insert into auth.users values('${b}','{"full_name":"Beto","username":"beto"}')`, 'closed registration rejected by trigger');
await db.exec(`insert into public.legal_documents values ('terms','v1','Test terms',repeat('Tests only. ',15),now()),('privacy','v1','Test privacy',repeat('Tests only. ',15),now()); update public.registration_settings set terms_version='v1',privacy_version='v1',signup_enabled=true,support_email='test@example.com';`);
await rejects(`update public.legal_documents set body=repeat('Different terms. ',15) where kind='terms'`, 'published content immutable');
await rejects(`insert into auth.users values('${b}','{"full_name":"Beto","username":"beto","terms_version":"v1","privacy_version":"v1","accepted_terms":true,"adult_confirmed":false}')`, 'minor declaration rejected');
await rejects(`insert into auth.users values('${b}','{"full_name":"Beto","username":"beto","terms_version":"old","privacy_version":"v1","accepted_terms":true,"adult_confirmed":true}')`, 'stale document version rejected');
await db.exec(`insert into auth.users values('${b}','{"full_name":"Beto","username":"beto","role":"admin","terms_version":"v1","privacy_version":"v1","accepted_terms":true,"adult_confirmed":true}');`);
check((await db.query(`select role from public.profiles where id='${b}'`)).rows[0].role,'user','metadata cannot grant admin');
check((await db.query(`select count(*)::int as n from public.legal_acceptances where user_id='${b}'`)).rows[0].n,1,'acceptance recorded without client session');
await db.exec(`set role anon;`);
await rejects(`select username from public.profiles`, 'anonymous table enumeration denied');
check((await db.query(`select is_username_available('beto') as available`)).rows[0].available,false,'public boolean availability works');
await rejects(`select * from public.legal_acceptances`,'anonymous acceptance denied');
await db.exec(`reset role; set role authenticated; select set_config('request.jwt.claim.sub','${a}',false);`);
check((await db.query('select username from public.profiles')).rows,[{username:'ana'}],'profile isolation');
await rejects(`update public.profiles set role='admin' where id='${a}'`,'role update denied');
await rejects(`delete from public.profiles where id='${a}'`,'client delete denied');
await rejects(`insert into public.legal_acceptances(user_id,terms_version,privacy_version,adult_confirmed) values('${a}','v1','v1',true)`,'client cannot forge acceptance history');
await rejects(`select accept_current_legal('v1','v1',false)`,'minor cannot accept through RPC');
await db.exec(`select accept_current_legal('v1','v1',true); select accept_current_legal('v1','v1',true);`);
check((await db.query('select count(*)::int as n from public.legal_acceptances')).rows[0].n,1,'own acceptance idempotent and isolated');
await rejects(`update public.legal_acceptances set accepted_at='2000-01-01'`,'history cannot be backdated');
await db.exec(`update public.profiles set bio=null,website='https://example.com/ana',interests=array['arte','musica'],onboarding_status='skipped' where id='${a}';`);
check((await db.query(`select interests,onboarding_status from public.profiles`)).rows[0],{interests:['arte','musica'],onboarding_status:'skipped'},'preferences persist');
await rejects(`update public.profiles set interests=array['sensitive-category'] where id='${a}'`,'unknown preference denied');
await rejects(`update public.profiles set website='javascript:alert(1)' where id='${a}'`,'unsafe link denied');
await rejects(`update public.profiles set avatar_path='${b}/33333333-3333-4333-8333-333333333333.png' where id='${a}'`,'foreign media denied');
await rejects(`select begin_profile_media_operation('${a}')`,'client cannot start privileged operation');
await db.exec(`reset role; insert into storage.objects(bucket_id,name) values('profile-media','${a}/33333333-3333-4333-8333-333333333333.png'),('profile-media','${b}/44444444-4444-4444-8444-444444444444.png'); set role authenticated;`);
check((await db.query('select count(*)::int as n from storage.objects')).rows[0].n,1,'storage read isolation');
await db.exec(`update public.profiles set avatar_path='${a}/33333333-3333-4333-8333-333333333333.png' where id='${a}'; update public.profiles set avatar_path=null where id='${a}';`);
check((await db.query('select avatar_path from public.profiles')).rows[0].avatar_path,null,'photo removal persists');
await db.exec('reset role');
const lease = (await db.query(`select begin_profile_media_operation('${a}') as id`)).rows[0].id;
check((await db.query(`select request_account_deletion('${a}') as ready`)).rows[0].ready,false,'deletion waits for in-flight upload');
await rejects(`select begin_profile_media_operation('${a}')`,'no new uploads after deletion mark');
await rejects(`update public.profiles set bio='late update' where id='${a}'`,'no profile edits while deleting');
await db.exec(`delete from public.profile_media_operations where id='${lease}';`);
check((await db.query(`select request_account_deletion('${a}') as ready`)).rows[0].ready,true,'retry can finish after upload');
await db.exec(`delete from storage.objects where name like '${a}/%'; delete from auth.users where id='${a}';`);
check((await db.query(`select count(*)::int as n from public.profiles where id='${a}'`)).rows[0].n,0,'profile cascades');
check((await db.query(`select count(*)::int as n from public.legal_acceptances where user_id='${a}'`)).rows[0].n,0,'acceptance retention matches deletion');
check((await db.query(`select count(*)::int as n from public.account_deletion_requests where user_id='${a}'`)).rows[0].n,0,'deletion marker cascades');
console.log(`${assertions} database assertions passed (isolated PostgreSQL via PGlite; hosted Supabase not contacted).`);
await db.close();
