// SQL/RLS tests in isolated PostgreSQL; never accesses the hosted database.
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const {PGlite} = await import(process.env.MAREA_PGLITE_MODULE || '@electric-sql/pglite');
const db = new PGlite(); let checks=0;
const eq=(actual,expected,label)=>{assert.deepEqual(actual,expected,label);checks++;};
const reject=async(sql,label)=>{await assert.rejects(db.exec(sql),undefined,label);checks++;};
const scalar=async(sql)=>Object.values((await db.query(sql)).rows[0])[0];
const a='11111111-1111-4111-8111-111111111111', b='22222222-2222-4222-8222-222222222222', c='33333333-3333-4333-8333-333333333333';
const login=async(id)=>db.exec(`reset role; set role authenticated; select set_config('request.jwt.claim.sub','${id}',false)`);
const system=async()=>db.exec("reset role; select set_config('request.jwt.claim.sub','',false)");
try {
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
create schema auth; create schema storage; grant usage on schema public,auth,storage to anon,authenticated,service_role;
create table auth.users(id uuid primary key,raw_user_meta_data jsonb not null default '{}');
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);
alter table storage.objects enable row level security; grant select,insert,update,delete on storage.objects to authenticated;
create function storage.foldername(name text) returns text[] language sql immutable as $$ select string_to_array(name,'/') $$;`);
const migration=async(name,optional=false)=>{try {await db.exec(await readFile(new URL(`../supabase/migrations/${name}.sql`,import.meta.url),'utf8'));}catch(e){if(!optional||e.code!=='ENOENT')throw e;}};
await migration('001_initial_schema');
for(const [id,name] of [[a,'autora'],[b,'lector'],[c,'tercero']])await db.query('insert into auth.users values($1,$2)',[id,{full_name:name,username:name}]);
for(const name of ['002_account_completion','003_community','004_post_locations','005_mission_lifecycle','006_profile_experience','007_minimal_registration','008_recover_minimal_registration'])await migration(name);
for(const name of ['009_post_reactions','010_post_comments','011_post_collaboration'])await migration(name,true);
eq(await scalar("select to_regclass('public.post_reactions') is not null"),true,'reactions must be persisted');
for(const id of [a,b,c]) {
 await login(id);
 await db.exec("select public.complete_initial_profile('Usuario general','{}','{}')");
}
await login(a);
const p=await scalar("insert into public.posts(kind,title,body,category) values('community','Publicación social','Descripción de prueba','arte') returning id");
await login(b);
await db.exec(`select public.set_post_reaction('${p}','inspire')`);
await db.exec(`select public.set_post_reaction('${p}','inspire')`);
eq(await scalar(`select reaction_count::int from public.post_social_stats(array['${p}'::uuid])`),1,'one reaction after retry');
await db.exec(`select public.set_post_reaction('${p}','support')`);
eq(await scalar(`select my_reaction from public.post_social_stats(array['${p}'::uuid])`),'support','change replaces selection');
eq(await scalar('select count(*)::int from public.notifications'),0,'actor cannot read recipient notifications');
await reject(`select public.set_post_reaction('${p}','invented')`,'invalid reaction denied');
await login(a);
eq(await scalar('select count(*)::int from public.notifications'),1,'one event after changing reaction');
const notification=await scalar('select id from public.notifications limit 1');
const cutoff=await scalar('select clock_timestamp()::text');
await db.exec(`select public.mark_notifications_read(null,'${cutoff}'::timestamptz)`);
eq(await scalar('select count(*)::int from public.notifications where read_at is null'),0,'mark existing entries');
await login(b);
await db.exec(`select public.set_post_reaction('${p}',null)`);
await login(a);
eq(await scalar('select count(*)::int from public.notifications'),0,'withdrawal removes reaction event');
await db.exec(`select public.set_post_reaction('${p}','like')`);
eq(await scalar('select count(*)::int from public.notifications'),0,'no self notification');
await login(b);
const operation='55555555-5555-4555-8555-555555555555';
const comment=await scalar(`select public.create_post_comment('${p}','Un comentario','${operation}')`);
eq(await scalar(`select public.create_post_comment('${p}','Un comentario','${operation}')`),comment,'comment retry returns same id');
eq(await scalar(`select comment_count::int from public.post_social_stats(array['${p}'::uuid])`),1,'comment retry does not duplicate');
await reject(`select public.create_post_comment('${p}',' ',gen_random_uuid())`,'blank comment denied');
await reject(`select public.create_post_comment('${p}',repeat('x',1001),gen_random_uuid())`,'comment maximum enforced');
await login(c);
await reject(`select public.delete_post_comment('${comment}')`,'third party cannot delete comment');
eq(await scalar(`select count(*)::int from public.post_comments where post_id='${p}'`),1,'visible comments readable');
await login(a);
eq(await scalar('select count(*)::int from public.notifications where read_at is null'),1,'new comment remains unread after earlier cutoff');
await db.exec(`select public.mark_notifications_read(null,'${cutoff}'::timestamptz)`);
eq(await scalar('select count(*)::int from public.notifications where read_at is null'),1,'cutoff cannot consume newer event');
await db.exec(`select public.delete_post_comment('${comment}')`);
eq(await scalar(`select comment_count::int from public.post_social_stats(array['${p}'::uuid])`),0,'post owner can remove comment');
await login(b);
await reject(`select public.send_post_interest('${p}','Quiero colaborar')`,'explicit invitation required');
await login(a); await db.exec(`update public.posts set allows_collaboration=true where id='${p}'`);
await reject(`select public.send_post_interest('${p}','Mi interés')`,'cannot collaborate with oneself');
await login(b);
const interest=await scalar(`select public.send_post_interest('${p}','Quiero colaborar')`);
eq(await scalar(`select public.send_post_interest('${p}','Quiero colaborar')`),interest,'one interest after retry');
eq(await scalar(`select interest_sent from public.post_social_stats(array['${p}'::uuid])`),true,'sender confirmed state');
await login(c);
eq(await scalar('select count(*)::int from public.post_collaboration_interests'),0,'interest message private');
await login(a);
eq(await scalar('select message from public.post_collaboration_interests'),'Quiero colaborar','author can read interest');
await login(c);
await db.exec(`select public.mark_notifications_read('${notification}',null)`);
await system();await db.exec(`update public.posts set hidden=true where id='${p}'`);
await login(b);
await reject(`select public.set_post_reaction('${p}','like')`,'hidden post cannot receive reaction');
await reject(`select public.create_post_comment('${p}','Oculto',gen_random_uuid())`,'hidden post cannot receive comment');
await reject(`select public.send_post_interest('${p}','Oculto')`,'hidden post cannot receive interest');
await system();await db.exec(`update public.posts set hidden=false where id='${p}'`);
await login(b);
await reject("insert into public.notifications(recipient_id,actor_id,post_id,kind,event_key) values(auth.uid(),auth.uid(),gen_random_uuid(),'reaction','spoof')",'client cannot forge notifications');
await system();await db.exec(`insert into public.account_deletion_requests(user_id) values('${a}')`);
await login(c);await reject(`select public.set_post_reaction('${p}','like')`,'post of deleting author cannot receive interactions');
await system();await db.exec(`delete from public.account_deletion_requests where user_id='${a}'`);
await system();await db.exec(`insert into public.account_deletion_requests(user_id) values('${b}')`);
await login(b);await reject(`select public.set_post_reaction('${p}','like')`,'deleting account cannot participate');
await system();await db.exec(`delete from public.posts where id='${p}'`);
eq(await scalar('select count(*)::int from public.post_reactions'),0,'post deletion cascades reactions');
eq(await scalar('select count(*)::int from public.post_collaboration_interests'),0,'post deletion cascades private interests');
eq(await scalar('select count(*)::int from public.notifications'),0,'post deletion cascades notifications');
await db.exec('set role anon');
await reject('select * from public.post_comments','anonymous content denied');
await reject('select * from public.notifications','anonymous notifications denied');
console.log(`Social database: ${checks} checks passed.`);
}finally{await db.close();}
