// Real PostgreSQL policies/RPCs in an isolated database; never touches hosted accounts.
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const {PGlite} = await import(process.env.MAREA_PGLITE_MODULE || '@electric-sql/pglite');
const db = new PGlite(); let checks = 0;
const eq = (actual, expected, label) => { assert.deepEqual(actual, expected, label); checks++; };
const reject = async (sql, label) => { await assert.rejects(db.exec(sql), undefined, label); checks++; };
const scalar = async (sql) => Object.values((await db.query(sql)).rows[0])[0];
const ids = ['11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222','33333333-3333-4333-8333-333333333333','44444444-4444-4444-8444-444444444444','55555555-5555-4555-8555-555555555555'];
const login = async (id) => db.exec(`reset role; set role authenticated; select set_config('request.jwt.claim.sub','${id}',false)`);
const system = async () => db.exec("reset role; select set_config('request.jwt.claim.sub','',false)");
const complete = (type) => `select public.complete_initial_profile('${type}',array['arte'],array['colaborar'])`;
const payload = (kind, extra={}) => JSON.stringify({kind,title:'Mi ficha',body:'Descripción de la ficha',category:'arte',status:'published',available:true,image_paths:[],...extra});
const save = (kind, extra={}, id=null) => `select public.save_showcase('${payload(kind,extra).replaceAll("'","''")}'::jsonb,${id ? `'${id}'::uuid` : 'null'})`;
try {
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
create schema auth; create schema storage; grant usage on schema public,auth,storage to anon,authenticated,service_role;
create table auth.users(id uuid primary key,raw_user_meta_data jsonb not null default '{}');
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);
alter table storage.objects enable row level security; grant select,insert,update,delete on storage.objects to authenticated;
create function storage.foldername(name text) returns text[] language sql immutable as $$ select string_to_array(name,'/') $$;`);
await db.exec(await readFile(new URL('../supabase/migrations/001_initial_schema.sql',import.meta.url),'utf8'));
for (const [i,id] of ids.entries()) await db.query('insert into auth.users values($1,$2)',[id,{full_name:`Persona ${i}`,username:`persona${i}`}]);
await db.exec(`update public.profiles set user_type='Artista / creador' where id='${ids[0]}'`);
for (const name of ['002_account_completion','003_community','004_post_locations','005_mission_lifecycle']) await db.exec(await readFile(new URL(`../supabase/migrations/${name}.sql`,import.meta.url),'utf8'));
await db.exec(`insert into public.posts(author_id,kind,title,body,category) values('${ids[0]}','project','Proyecto histórico','Un proyecto anterior','arte')`);
try { await db.exec(await readFile(new URL('../supabase/migrations/006_profile_experience.sql',import.meta.url),'utf8')); } catch(e) { if(e.code!=='ENOENT') throw e; }
await login(ids[0]);
await reject("update public.profiles set user_type='Negocio'",'direct profile type changes denied even before confirmation');
await reject("update public.profiles set interests=array['musica']",'direct preference changes denied');
await reject("update public.profiles set onboarding_status='skipped'",'old client cannot skip onboarding');
await reject("update public.profiles set initial_profile_completed_at=now()",'cannot forge confirmation timestamp');
await reject("select public.complete_initial_profile('Negocio','{}',array['colaborar'])",'interests required');
await reject("select public.complete_initial_profile('Negocio',array['arte'],'{}')",'goal required');
await reject("select public.complete_initial_profile('Negocio',array['unknown'],array['colaborar'])",'unknown interest rejected');
await reject(save('service'),'no showcase before initial confirmation');
await db.exec(complete('Artista / creador'));
await reject(complete('Negocio'),'second initial confirmation denied');
await reject("update public.profiles set role='admin'",'admin role remains private');
await db.exec("update public.profiles set bio='Nueva bio'");
eq(await scalar('select bio from public.profiles'),'Nueva bio','ordinary edits still work');
eq(await scalar('select count(*)::int from public.posts'),1,'historical post preserved');
const image = `${ids[0]}/aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa.png`;
await db.exec(`insert into storage.objects(bucket_id,name) values('showcase-media','${image}')`);
await reject(save('project'),'published project needs photo');
await reject(save('product',{image_paths:[image]}),'artist cannot create products');
const work = await scalar(save('project',{image_paths:[image]}));
await db.exec(`select public.report_showcase('${work}','Contenido inapropiado')`);
const draft = await scalar(save('project',{status:'draft',body:''}));
await login(ids[1]); await db.exec(complete('Usuario general'));
eq(await scalar('select count(*)::int from public.showcase_items'),1,'draft hidden from visitor');
await reject(save('service'),'general cannot create professional ficha');
await reject(save('project',{image_paths:[image]},work),'cannot update another owner ficha');
await reject(`select public.delete_showcase('${work}')`,'cannot delete another owner ficha');
await db.exec(`insert into public.showcase_saves(item_id) values('${work}')`);
await reject(`insert into public.showcase_saves(item_id) values('${draft}')`,'cannot save draft');
eq(await scalar(`select count(*)::int from storage.objects where name='${image}'`),1,'published photo visible');
await login(ids[2]); await db.exec(complete('Emprendedor'));
await reject(save('product',{price:-1}),'negative price denied');
const service = await scalar(save('service',{price:150}));
await reject(save('service',{image_paths:[image]}),'foreign photo denied');
await login(ids[3]); await db.exec(complete('Negocio'));
await db.exec("update public.profiles set business_hours='{\"mon\":\"09:00-18:00\",\"sun\":null}',contact_url='https://example.com/contacto',location='Centro'");
await reject("update public.profiles set business_hours='{\"mon\":\"18:00-09:00\"}'",'invalid hours denied');
await reject("update public.profiles set contact_url='javascript:alert(1)'",'unsafe contact URL denied');
await scalar(save('service'));
await db.exec("insert into public.posts(kind,title,body,category) values('service','Servicio público','Una novedad','arte')");
await login(ids[2]);
await db.exec(save('service',{available:false},service));
await login(ids[1]); eq(await scalar(`select count(*)::int from public.showcase_items where id='${service}'`),0,'unavailable item hidden from visitors');
await login(ids[0]);
await db.exec(save('project',{status:'archived',image_paths:[image]},work));
await login(ids[1]); eq(await scalar(`select count(*)::int from public.showcase_items where id='${work}'`),0,'archived work hidden');
await login(ids[0]); await db.exec(save('project',{image_paths:[image]},work));
await system(); await db.exec(`update public.profiles set role='admin' where id='${ids[4]}'`);
await login(ids[4]); await db.exec(complete('Usuario general'));
await db.exec(`select public.moderate_content('${work}','showcase',true)`);
await login(ids[1]); eq(await scalar(`select count(*)::int from public.showcase_items where id='${work}'`),0,'moderated ficha hidden');
eq(await scalar(`select count(*)::int from storage.objects where name='${image}'`),0,'moderated image hidden');
await login(ids[0]); await db.exec(save('project',{image_paths:[image]},work));
eq(await scalar(`select hidden from public.showcase_items where id='${work}'`),true,'owner edits cannot undo moderation');
await login(ids[4]); await db.exec(`select public.moderate_content('${work}','showcase',false)`);
await login(ids[1]);
const directory = (await db.query(`select * from public.community_profiles(array['${ids[0]}'::uuid])`)).rows[0];
for(const field of ['interests','goals','role','email','initial_profile_completed_at']) eq(field in directory,false,`${field} not in public directory`);
await login(ids[0]);
await db.exec(`select public.delete_showcase('${work}')`);
await db.exec(`delete from storage.objects where bucket_id='showcase-media' and name='${image}'`);
eq(await scalar(`select count(*)::int from storage.objects where name='${image}'`),0,'unused photograph deletable');
await system(); await db.exec(`delete from auth.users where id='${ids[0]}'`);
eq(await scalar(`select count(*)::int from public.showcase_items where owner_id='${ids[0]}'`),0,'account deletion cascades');
console.log(`${checks} profile experience checks passed (isolated PostgreSQL).`);
} finally {await db.close();}
